import Jupiter from '../assets/jupiter_96159.ico'
import Marte from '../assets/mars_96191.ico'
import Mercurio from '../assets/mercury_9123.ico'
import Lua from '../assets/moonfullmoon_96213.ico'
import Neturno from '../assets/neptune_96229.ico'
import Saturno from '../assets/saturn_96158.ico'
import Venus from '../assets/venus_96156.ico'
import Urano from '../assets/uranus_96171.ico'

export const paises = ["","Afeganistão", 
 "África do Sul", 
 "Albânia", 
 "Alemanha", 
 "Andorra", 
 "Angola", 
 "Antigua e Barbuda", 
 "Arábia Saudita", 
 "Argélia", 
 "Argentina", 
 "Arménia", 
 "Austrália", 
 "Áustria", 
 "Azerbaijão", 
 "Bahamas", 
 "Bangladexe", 
 "Barbados", 
 "Barém", 
 "Bélgica", 
 "Belize", 
 "Benim", 
 "Bielorrússia", 
 "Bolívia", 
 "Bósnia e Herzegovina", 
 "Botsuana", 
 "Brasil", 
 "Brunei", 
 "Bulgária", 
 "Burquina Faso", 
 "Burúndi", 
 "Butão", 
 "Cabo Verde", 
 "Camarões", 
 "Camboja", 
 "Canadá", 
 "Catar", 
 "Cazaquistão", 
 "Chade", 
 "Chile", 
 "China", 
 "Chipre", 
 "Colômbia", 
 "Comores", 
 "Congo-Brazzaville", 
 "Coreia do Norte", 
 "Coreia do Sul", 
 "Cosovo", 
 "Costa do Marfim", 
 "Costa Rica", 
 "Croácia", 
 "Cuaite", 
 "Cuba", 
 "Dinamarca", 
 "Dominica", 
 "Egito", 
 "Emirados Árabes Unidos", 
 "Equador", 
 "Eritreia", 
 "Eslováquia", 
 "Eslovénia", 
 "Espanha", 
 "Estado da Palestina", 
 "Estados Unidos", 
 "Estónia", 
 "Etiópia", 
 "Fiji", 
 "Filipinas", 
 "Finlândia", 
 "França", 
 "Gabão", 
 "Gâmbia", 
 "Gana", 
 "Geórgia", 
 "Granada", 
 "Grécia", 
 "Guatemala", 
 "Guiana", 
 "Guiné", 
 "Guiné Equatorial", 
 "Guiné-Bissau", 
 "Haiti", 
 "Honduras", 
 "Hungria", 
 "Iémen", 
 "Ilhas Marechal", 
 "Índia", 
 "Indonésia", 
 "Irão", 
 "Iraque", 
 "Irlanda", 
 "Islândia", 
 "Israel", 
 "Itália", 
 "Jamaica", 
 "Japão", 
 "Jibuti", 
 "Jordânia", 
 "Laus", 
 "Lesoto", 
 "Letónia", 
 "Líbano", 
 "Libéria", 
 "Líbia", 
 "Listenstaine", 
 "Lituânia", 
 "Luxemburgo", 
 "Macedónia", 
 "Madagáscar", 
 "Malásia", 
 "Maláui", 
 "Maldivas", 
 "Mali", 
 "Malta", 
 "Marrocos", 
 "Maurícia", 
 "Mauritânia", 
 "México", 
 "Mianmar", 
 "Micronésia", 
 "Moçambique", 
 "Moldávia", 
 "Mónaco", 
 "Mongólia", 
 "Montenegro", 
 "Namíbia", 
 "Nauru", 
 "Nepal", 
 "Nicarágua", 
 "Níger", 
 "Nigéria", 
 "Noruega", 
 "Nova Zelândia", 
 "Omã", 
 "Países Baixos", 
 "Palau", 
 "Panamá", 
 "Papua Nova Guiné", 
 "Paquistão", 
 "Paraguai", 
 "Peru", 
 "Polónia", 
 "Portugal", 
 "Quénia", 
 "Quirguistão", 
 "Quiribáti", 
 "Reino Unido", 
 "República Centro-Africana", 
 "República Checa", 
 "República Democrática do Congo", 
 "República Dominicana", 
 "Roménia", 
 "Ruanda", 
 "Rússia", 
 "Salomão", 
 "Salvador", 
 "Samoa", 
 "Santa Lúcia", 
 "São Cristóvão e Neves", 
 "São Marinho", 
 "São Tomé e Príncipe", 
 "São Vicente e Granadinas", 
 "Seicheles", 
 "Senegal", 
 "Serra Leoa", 
 "Sérvia", 
 "Singapura", 
 "Síria", 
 "Somália", 
 "Sri Lanca", 
 "Suazilândia", 
 "Sudão", 
 "Sudão do Sul", 
 "Suécia", 
 "Suíça", 
 "Suriname", 
 "Tailândia", 
 "Taiuã", 
 "Tajiquistão", 
 "Tanzânia", 
 "Timor-Leste", 
 "Togo", 
 "Tonga", 
 "Trindade e Tobago", 
 "Tunísia", 
 "Turcomenistão", 
 "Turquia", 
 "Tuvalu", 
 "Ucrânia", 
 "Uganda", 
 "Uruguai", 
 "Usbequistão", 
 "Vanuatu", 
 "Vaticano", 
 "Venezuela", 
 "Vietname", 
 "Zâmbia", 
 "Zimbábue"]
export const imgPlanets = [
   Jupiter,
   Lua,
   Marte,
   Mercurio,
   Neturno,
   Saturno,
   Urano,
   Venus
]
 export const planetList = [
   'Júpiter',
   'Lua',
   'Marte', 
   'Mercúrio',
   'Neturno',
    'Saturno',
    'Urano',
    'Vênus' 
 ]
