###
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name":"Jana",
    "email":"jasd@gmail.com",
    "password":"12345"
}
###
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email":"j@gmail.com",
    "password":"12345"
}

###

###
POST http://localhost:3003/posts/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgwMWMyNjAwLTIyOTUtNDM1My1hMTAxLTMwZjk2MjBkNzIzNiIsImlhdCI6MTYyNDIyNjg4NywiZXhwIjoxNjI0MjI4MzI3fQ.vt3U5NVbHjfhD1R93LCh7aTMuLTbPcjByAxXB8nCmb8
Content-Type: application/json

{
    "photo":"sadas",
    "description":"asd",
    "type": "normal" 
}

###
POSt http://localhost:3003/users/friendship/5bd4c42e-eb0a-47f5-83f1-979b93b4d676
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUxOTJiNDUzLTkzMzUtNDc4Zi1iOTk2LTBhMzZiNDIwNDU2YSIsImlhdCI6MTYyNDIyNzQ4OSwiZXhwIjoxNjI0MzEzODg5fQ.hihBlhw93R5RII7_3JcKhISn6x3unvbcGvbNkHNu7b0
